name: Broken link check
on:
  schedule:
    # every day at midnight
    - cron: '0 0 * * *'  
    
jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:

      - name: Check dev.risczero.com links
        id: link-report-devdocs
        uses: risc0/link-checker@v1.0.2
        with:
          url: "https://dev.risczero.com"
          honorRobotExclusions: false
          ignorePatterns: ""
          recursiveLinks: true

      - name: Get the result
        run: echo "${{steps.link-report-devdocs.outputs.result}}"

      - name: Check risczero.com links
        id: link-report-risczero
        uses: risc0/link-checker@v1.0.2
        with:
          url: "https://risczero.com"
          honorRobotExclusions: false
          ignorePatterns: "linkedin.com/company/risczero,twitter"
          recursiveLinks: true

      - name: Get the result
        run: echo "${{steps.link-report-risczero.outputs.result}}"

      - name: Check bonsai.xyz links
        id: link-report-bonsai
        uses: risc0/link-checker@v1.0.2
        with:
          url: "https://bonsai.xyz"
          honorRobotExclusions: false
          ignorePatterns: ""
          recursiveLinks: true

      - name: Get the result
        run: echo "${{steps.link-report-bonsai.outputs.result}}"
